repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: file-contents-sorter
        files: docs/spelling_wordlist.txt
-   repo: https://github.com/pycqa/doc8
    rev: v1.1.1
    hooks:
    -   id: doc8
-   repo: https://github.com/adamchainz/django-upgrade
    rev: 1.15.0
    hooks:
    -   id: django-upgrade
        args: [--target-version, "3.2"]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: rst-backticks
    -   id: rst-directive-colons
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
    -   id: prettier
        entry: env PRETTIER_LEGACY_CLI=1 prettier
        types_or: [javascript, css]
        args:
        - --trailing-comma=es5
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0-alpha.0
    hooks:
    -   id: eslint
        files: \.js?$
        types: [file]
        args:
        - --fix
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.1.9'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
-   repo: https://github.com/tox-dev/pyproject-fmt
    rev: 1.5.3
    hooks:
      - id: pyproject-fmt
-   repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.15
    hooks:
      - id: validate-pyproject
